/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { InferenceClaim } from "./InferenceClaim";
export * as factories from "./factories";
export { InferenceClaim__factory } from "./factories/InferenceClaim__factory";
