/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace InferenceClaim {
  export type ClaimStruct = {
    provider: AddressLike;
    modelHash: BytesLike;
    inputHash: BytesLike;
    outputHash: BytesLike;
    submittedAt: BigNumberish;
    challenger: AddressLike;
    status: BigNumberish;
  };

  export type ClaimStructOutput = [
    provider: string,
    modelHash: string,
    inputHash: string,
    outputHash: string,
    submittedAt: bigint,
    challenger: string,
    status: bigint
  ] & {
    provider: string;
    modelHash: string;
    inputHash: string;
    outputHash: string;
    submittedAt: bigint;
    challenger: string;
    status: bigint;
  };
}

export interface InferenceClaimInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CHALLENGE_WINDOW"
      | "challengeClaim"
      | "claims"
      | "finalizeClaim"
      | "getChallengeDeadline"
      | "getClaim"
      | "nextClaimId"
      | "revealOutput"
      | "submitClaim"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimChallenged"
      | "ClaimFinalized"
      | "ClaimSubmitted"
      | "OutputRevealed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "CHALLENGE_WINDOW",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "challengeClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claims",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getChallengeDeadline",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaim",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextClaimId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revealOutput",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitClaim",
    values: [BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CHALLENGE_WINDOW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "challengeClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claims", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeClaim",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChallengeDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getClaim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextClaimId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revealOutput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitClaim",
    data: BytesLike
  ): Result;
}

export namespace ClaimChallengedEvent {
  export type InputTuple = [claimId: BigNumberish, challenger: AddressLike];
  export type OutputTuple = [claimId: bigint, challenger: string];
  export interface OutputObject {
    claimId: bigint;
    challenger: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimFinalizedEvent {
  export type InputTuple = [claimId: BigNumberish, finalStatus: BigNumberish];
  export type OutputTuple = [claimId: bigint, finalStatus: bigint];
  export interface OutputObject {
    claimId: bigint;
    finalStatus: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimSubmittedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    provider: AddressLike,
    modelHash: BytesLike,
    inputHash: BytesLike,
    outputHash: BytesLike,
    challengeDeadline: BigNumberish
  ];
  export type OutputTuple = [
    claimId: bigint,
    provider: string,
    modelHash: string,
    inputHash: string,
    outputHash: string,
    challengeDeadline: bigint
  ];
  export interface OutputObject {
    claimId: bigint;
    provider: string;
    modelHash: string;
    inputHash: string;
    outputHash: string;
    challengeDeadline: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OutputRevealedEvent {
  export type InputTuple = [
    claimId: BigNumberish,
    honest: boolean,
    rawOutput: BytesLike
  ];
  export type OutputTuple = [
    claimId: bigint,
    honest: boolean,
    rawOutput: string
  ];
  export interface OutputObject {
    claimId: bigint;
    honest: boolean;
    rawOutput: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InferenceClaim extends BaseContract {
  connect(runner?: ContractRunner | null): InferenceClaim;
  waitForDeployment(): Promise<this>;

  interface: InferenceClaimInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CHALLENGE_WINDOW: TypedContractMethod<[], [bigint], "view">;

  challengeClaim: TypedContractMethod<
    [claimId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claims: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, string, bigint] & {
        provider: string;
        modelHash: string;
        inputHash: string;
        outputHash: string;
        submittedAt: bigint;
        challenger: string;
        status: bigint;
      }
    ],
    "view"
  >;

  finalizeClaim: TypedContractMethod<
    [claimId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getChallengeDeadline: TypedContractMethod<
    [claimId: BigNumberish],
    [bigint],
    "view"
  >;

  getClaim: TypedContractMethod<
    [claimId: BigNumberish],
    [InferenceClaim.ClaimStructOutput],
    "view"
  >;

  nextClaimId: TypedContractMethod<[], [bigint], "view">;

  revealOutput: TypedContractMethod<
    [claimId: BigNumberish, rawOutput: BytesLike],
    [void],
    "nonpayable"
  >;

  submitClaim: TypedContractMethod<
    [modelHash: BytesLike, inputHash: BytesLike, outputHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CHALLENGE_WINDOW"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "challengeClaim"
  ): TypedContractMethod<[claimId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claims"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, string, bigint, string, bigint] & {
        provider: string;
        modelHash: string;
        inputHash: string;
        outputHash: string;
        submittedAt: bigint;
        challenger: string;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeClaim"
  ): TypedContractMethod<[claimId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getChallengeDeadline"
  ): TypedContractMethod<[claimId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClaim"
  ): TypedContractMethod<
    [claimId: BigNumberish],
    [InferenceClaim.ClaimStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextClaimId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "revealOutput"
  ): TypedContractMethod<
    [claimId: BigNumberish, rawOutput: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitClaim"
  ): TypedContractMethod<
    [modelHash: BytesLike, inputHash: BytesLike, outputHash: BytesLike],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimChallenged"
  ): TypedContractEvent<
    ClaimChallengedEvent.InputTuple,
    ClaimChallengedEvent.OutputTuple,
    ClaimChallengedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimFinalized"
  ): TypedContractEvent<
    ClaimFinalizedEvent.InputTuple,
    ClaimFinalizedEvent.OutputTuple,
    ClaimFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "ClaimSubmitted"
  ): TypedContractEvent<
    ClaimSubmittedEvent.InputTuple,
    ClaimSubmittedEvent.OutputTuple,
    ClaimSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OutputRevealed"
  ): TypedContractEvent<
    OutputRevealedEvent.InputTuple,
    OutputRevealedEvent.OutputTuple,
    OutputRevealedEvent.OutputObject
  >;

  filters: {
    "ClaimChallenged(uint256,address)": TypedContractEvent<
      ClaimChallengedEvent.InputTuple,
      ClaimChallengedEvent.OutputTuple,
      ClaimChallengedEvent.OutputObject
    >;
    ClaimChallenged: TypedContractEvent<
      ClaimChallengedEvent.InputTuple,
      ClaimChallengedEvent.OutputTuple,
      ClaimChallengedEvent.OutputObject
    >;

    "ClaimFinalized(uint256,uint8)": TypedContractEvent<
      ClaimFinalizedEvent.InputTuple,
      ClaimFinalizedEvent.OutputTuple,
      ClaimFinalizedEvent.OutputObject
    >;
    ClaimFinalized: TypedContractEvent<
      ClaimFinalizedEvent.InputTuple,
      ClaimFinalizedEvent.OutputTuple,
      ClaimFinalizedEvent.OutputObject
    >;

    "ClaimSubmitted(uint256,address,bytes32,bytes32,bytes32,uint256)": TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;
    ClaimSubmitted: TypedContractEvent<
      ClaimSubmittedEvent.InputTuple,
      ClaimSubmittedEvent.OutputTuple,
      ClaimSubmittedEvent.OutputObject
    >;

    "OutputRevealed(uint256,bool,bytes)": TypedContractEvent<
      OutputRevealedEvent.InputTuple,
      OutputRevealedEvent.OutputTuple,
      OutputRevealedEvent.OutputObject
    >;
    OutputRevealed: TypedContractEvent<
      OutputRevealedEvent.InputTuple,
      OutputRevealedEvent.OutputTuple,
      OutputRevealedEvent.OutputObject
    >;
  };
}
